const COLLECTION_USERS = "users";
const COLLECTION_FRIEND_REQUEST = "friendRequests";
const COLLECTION_NOTIFICATIONS = "notifications";
const EVENTS_COLLECTION = "events";

export {
  COLLECTION_USERS,
  COLLECTION_FRIEND_REQUEST,
  COLLECTION_NOTIFICATIONS,
  EVENTS_COLLECTION,
};
